version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - npm run lint
      - ng test --watch=false --browsers=ChromeHeadless || true

  build:
    commands:
      - ng build 

artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
